CREATE TABLE [dbo].[UserEvent] (
    [ID]      INT IDENTITY (1, 1) NOT NULL,
    [UserID]  INT NOT NULL,
    [EventID] INT NOT NULL,
    CONSTRAINT [PK_UserEvent] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_UserEvent_Event] FOREIGN KEY ([EventID]) REFERENCES [dbo].[Event] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_UserEvent_User] FOREIGN KEY ([UserID]) REFERENCES [dbo].[User] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);

